insert into public.afirmaciones_banco (id, foco, texto, ejercicio) values
  ('d1', 'dialogo', 'Hoy me hablo como le hablaría a alguien que amo.', 'Escribe una frase que te dijiste hoy con dureza. Reescríbela como se la dirías a tu mejor amiga.'),
  ('d2', 'dialogo', 'No soy mis peores pensamientos sobre mí misma.', 'Nombra 1 cosa que hiciste bien hoy, por pequeña que sea.'),
  ('d3', 'dialogo', 'Puedo equivocarme y seguir mereciendo respeto propio.', 'Recuerda un error reciente. Di en voz alta: ''me equivoqué, no soy un error''.'),
  ('d4', 'dialogo', 'Mi valor no depende de ser perfecta hoy.', 'Haz una lista de 3 cosas que te gustan de ti que no tienen que ver con logros.'),
  ('d5', 'dialogo', 'Puedo notar la voz crítica sin obedecerla.', 'Cuando aparezca la voz dura, ponle un nombre. Dile: ''te escucho, pero hoy no decides tú''.'),
  ('d6', 'dialogo', 'Merezco la misma paciencia que le doy a los demás.', 'Piensa en alguien a quien tratas con paciencia. Trátate así 10 minutos hoy.'),
  ('d7', 'dialogo', 'Ser dura conmigo no me hizo más fuerte, solo más cansada.', 'Anota una exigencia que te pones y pregúntate: ¿se la pediría a alguien que quiero?'),
  ('d8', 'dialogo', 'Puedo estar orgullosa de intentarlo, no solo de lograrlo.', 'Nombra algo que intentaste esta semana, sin importar el resultado.'),
  ('d9', 'dialogo', 'No tengo que resolverlo todo hoy para ser suficiente.', 'Escribe: ''a mi edad debería tener esto resuelto''. Ahora tacha ''debería'' y sigue leyendo la frase.'),
  ('d10', 'dialogo', 'Ser exigente conmigo no es lo mismo que ser justa conmigo.', 'Nombra una regla que te impones y que no le pedirías a nadie más.'),
  ('d11', 'dialogo', 'Puedo corregir un error sin castigarme por él.', 'Piensa en algo que ''hiciste mal'' hoy. Nombra qué vas a hacer distinto, sin insultarte primero.'),
  ('d12', 'dialogo', 'Mi crítica interna exagera; yo decido si le creo.', 'La próxima vez que te digas algo duro, pregúntate: ¿esto es un hecho o solo mi voz de siempre?'),
  ('d13', 'dialogo', 'Hoy elijo hablarme como alguien que quiere que yo crezca, no que me rinda.', 'Cambia una frase de hoy de ''soy un desastre'' a ''hoy tuve un día difícil''.'),
  ('d14', 'dialogo', 'No necesito ser perfecta para merecer descanso.', 'Date permiso de parar 5 minutos sin justificarlo con nada que ''lograste''.'),
  ('p1', 'panico', 'Mi cuerpo sabe calmarse, aunque ahora no lo sienta.', 'Pon una mano en el pecho y otra en el abdomen. Respira 4 veces, sintiendo cómo se mueven.'),
  ('p2', 'panico', 'Esta sensación es incómoda, pero no peligrosa.', 'Nombra 5 cosas que puedes ver ahora mismo, en voz baja o mental.'),
  ('p3', 'panico', 'No estoy sola: sé exactamente qué hacer cuando esto pase.', 'Recuerda dónde está tu botón SOS en la app. Tócalo una vez ahora, solo para practicar.'),
  ('p4', 'panico', 'Ya pasé por esto antes y logré calmarme.', 'Escribe la última vez que una crisis pasó. ¿Cuánto duró en realidad?'),
  ('p5', 'panico', 'Puedo sentir miedo y seguir estando a salvo.', 'Cuenta hacia atrás desde 20 de 3 en 3, despacio.'),
  ('p6', 'panico', 'El pánico tiene un principio, un punto máximo y un final.', 'Si sientes opresión en el pecho, estira los brazos hacia arriba y exhala largo 3 veces.'),
  ('p7', 'panico', 'No tengo que controlar todo para estar bien.', 'Suelta los hombros. Nota si los tenías apretados sin darte cuenta.'),
  ('p8', 'panico', 'Puedo estar sola y aun así estar acompañada por lo que sé hacer.', 'Escribe 3 palabras que te digas cuando el miedo empieza: te van a servir la próxima vez.'),
  ('p9', 'panico', 'No estoy en peligro, mi cuerpo solo está en alerta.', 'Moja tus manos con agua fría o sostenlas bajo la llave un momento. El frío ayuda a bajar la alerta.'),
  ('p10', 'panico', 'Cada vez que atravieso esto, se vuelve un poco menos aterrador.', 'Recuerda: la última vez pensaste que no ibas a poder, y pudiste. Anótalo.'),
  ('p11', 'panico', 'Puedo pedir ayuda sin sentir que fallé.', 'Si puedes, avísale a alguien de confianza: ''estoy teniendo un momento difícil''. No tienes que explicar más.'),
  ('p12', 'panico', 'Mi respiración es algo que sí puedo controlar ahora mismo.', 'Inhala contando 4, sostén 4, exhala contando 6. Repite 4 veces.'),
  ('a1', 'abandono', 'Hoy solo necesito 2 minutos, no una hora perfecta.', 'Haz el Ritual de hoy sin pensar en si lo vas a mantener para siempre. Solo hoy.'),
  ('a2', 'abandono', 'Empezar de nuevo no es fracasar, es seguir intentando.', 'Si dejaste de venir unos días, no hay que ''recuperar'' nada. Vuelve a hoy.'),
  ('a3', 'abandono', 'No necesito una racha perfecta para que esto valga la pena.', 'Marca el día de hoy como completo, sin mirar cuántos días fallaste antes.'),
  ('a4', 'abandono', 'Esta vez no es solo una notificación, es algo que hago con mis manos.', 'Escribe una palabra que describa cómo te sientes ahora mismo.'),
  ('a5', 'abandono', 'Puedo construir este hábito a mi propio ritmo.', 'Elige: ¿hoy quieres 2 minutos o solo 30 segundos? Ambos cuentan.'),
  ('a6', 'abandono', 'No es que no pueda sostener esto, es que antes nada me daba herramientas de verdad.', 'Compara: hoy hiciste algo con tus manos, no solo leíste una notificación. Anótalo.'),
  ('a7', 'abandono', 'Volver después de una pausa también es parte del proceso.', 'Si hoy es tu primer día en un tiempo, no te expliques por qué faltaste. Solo dale al Ritual.'),
  ('a8', 'abandono', 'Sanar no tiene que costar como si fuera un lujo para poder sostenerlo.', 'Recuerda que esto no depende de gastar más — depende de que aparezcas hoy, 2 minutos.'),
  ('a9', 'abandono', 'Esta vez estoy construyendo algo mío, no siguiendo una lista ajena.', 'Elige tú cómo quieres hacer el Ritual hoy: en silencio, en voz alta, o escribiéndolo.'),
  ('o1', 'otra', 'Cada día que me elijo a mí misma cuenta, aunque sea pequeño.', 'Anota una cosa que hiciste hoy solo porque te hacía bien a ti.'),
  ('o2', 'otra', 'Merezco el mismo cuidado que le doy a quienes amo.', 'Haz algo amable por ti en los próximos 10 minutos: agua, estirar, respirar.'),
  ('o3', 'otra', 'Estoy construyendo una relación distinta conmigo misma.', 'Nombra algo que hoy hiciste diferente a como lo hubieras hecho hace un año.'),
  ('o4', 'otra', 'No tengo que tenerlo todo resuelto para merecer paz.', 'Suelta por 2 minutos algo que estás tratando de resolver ahora mismo.'),
  ('o5', 'otra', 'Lo que siento hoy es válido, aunque no tenga un nombre claro todavía.', 'Escribe una palabra que resuma cómo te sientes ahora, sin juzgarla.'),
  ('o6', 'otra', 'Cuidarme no es egoísmo, es lo que me permite cuidar lo demás.', 'Nombra una responsabilidad que hoy puedes soltar 10 minutos, solo para respirar.'),
  ('o7', 'otra', 'Puedo avanzar despacio y seguir avanzando.', 'Elige un paso pequeño para hoy — no el paso perfecto, solo uno posible.'),
  ('o8', 'otra', 'Merezco espacio para simplemente estar, sin producir nada.', 'Quédate quieta 60 segundos sin hacer nada ''útil''. Solo respira.')
on conflict (id) do nothing;

-- total rows: 43
